name: build-and-test

on: 
  push:

jobs:

  BuildAndTest:

    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Installing valgring and cpplint
      run: |
          sudo apt install valgrind
          sudo pip install cpplint
          
    - name: Test them all
      run: make all
          CODECOV_TOKEN='b83b0448-2100-409f-8683-23d714f165a9'
          bash <(curl -s https://codecov.io/bash)
